name: develop

on:
  push:
    branches:
      - "develop"
jobs:
  check_macos:
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew --no-daemon check
  check_windows:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v2
      - run: CALL gradlew.bat --no-daemon check
        shell: cmd
  check_deploy_linux:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew --no-daemon check
      - run: ./gradlew --no-daemon publishDevelop -PdevBuildNumber='$GITHUB_RUN_NUMBER' -PpearxRepoUsername='${{ secrets.PEARX_REPO_USERNAME }}' -PpearxRepoPassword='${{ secrets.PEARX_REPO_PASSWORD }}'